# Teoria de Juegos
## Autor: Edinson Tolentino
### Tema : Equilibrio de Nash
### Juego dilema del prisionero

El siguiente juego, muestra las decisiones de dos posibles sospesochos de un crimen:
- J2 (jugador columa)
- J1 (jugador fila)

|       | Confesar | No Confesar |
|-------|--------|-------|
|Confesar |  -5,-5   | 0,-10      | 
|No Confesar  |  -10,0      | -1,-1      |

In [3]:
import nashpy as nash
import numpy  as np

In [4]:
J1 = np.array([[-5,0], [-10,-1]])
J2 = np.array([[-5,-10],[0,-1]])
out1 = nash.Game(J1,J2)
out1

Bi matrix game with payoff matrices:

Row player:
[[ -5   0]
 [-10  -1]]

Column player:
[[ -5 -10]
 [  0  -1]]

Solución de equilibrio de Nash

In [5]:
eq = out1.support_enumeration()
for N in eq:
    print(N)
    

(array([1., 0.]), array([1., 0.]))


Por tanto, se puede observar:
- El J1 (jugador fila) es confesar : 100 \% de elección
- El J2 (jugador columna) es confesar: 100 \% de eleción

Calculando las utilidades obtenidas en base a la elección de las estrategias

Entonces la Utilidad de cada jugador
- Estrategia de jugador fila : $\sigma_{r}=(1,0)$
- Estrategia de columna fila : $\sigma_{c}=(1,0)$


$$
U_{1} = \sigma_{r} A_{1} \sigma^{T}_{c}
$$

$$
U_{2} = \sigma_{r} A_{2} \sigma^{T}_{c}
$$

In [16]:
sigma_r = np.array([1, 0])
sigma_c = np.array([1, 0])


Por tanto, para calcular el valor de la utilidad del primer jugador

$$
U_{1} = \sigma_{r} A_{1} \sigma^{T}_{c}
$$

$$
U_{1} =  \begin{bmatrix} 1 & 0    \end{bmatrix} x  \begin{bmatrix} -5 & 0  \\ -10 & -1  \end{bmatrix} x \begin{bmatrix} 1 & \\ 0 &    \end{bmatrix}
$$

$$
U_{1} =  \begin{bmatrix} -5 & 0    \end{bmatrix}  x \begin{bmatrix} 1 & \\ 0 &    \end{bmatrix}
$$

$$
U_{1} =-5
$$

Por otro lado, para calcular el valor de la utilidad del segundo jugador

$$
U_{2} = \sigma_{r} A_{2} \sigma^{T}_{c}
$$

$$
U_{2} =  \begin{bmatrix} 1 & 0    \end{bmatrix} x  \begin{bmatrix} -5 & -10  \\ 0 & -1  \end{bmatrix} x \begin{bmatrix} 1 & \\ 0 &    \end{bmatrix}
$$

$$
U_{2} =  \begin{bmatrix} -5 & 0    \end{bmatrix}  x \begin{bmatrix} 1 & \\ 0 &    \end{bmatrix}
$$

$$
U_{2} =-5
$$

In [18]:
Utilidad_1 = out1[sigma_r, sigma_c]
Utilidad_1

array([-5, -5])

### Juegos de pennies

El siguiente juego, muestra las decisiones de las estrategias (cara y sello):
- A2 (jugador columa)
- A1 (jugador fila)

|       | Cara | Sello |
|-------|--------|-------|
|Cara |  1,-1   | -1,1      | 
|Sello  |  -1,1      | 1,-1      |

In [11]:
A1 = np.array([[1,-1], [-1,1]])
A2 = np.array([[-1,1],[1,-1]])
out2 = nash.Game(A1,A2)
out2

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [12]:
ec = out2.support_enumeration()
for Z in ec:
    print(Z)

(array([0.5, 0.5]), array([0.5, 0.5]))


Calculando la Utilidad de cada jugador
- Estrategia de jugador fila : $\sigma_{r}$
- Estrategia de columna fila : $\sigma_{c}$


$$
U_{1} = \sigma_{r} A_{1} \sigma^{T}_{c}
$$

$$
U_{2} = \sigma_{r} A_{2} \sigma^{T}_{c}
$$


In [13]:
sigma_r = np.array([0.5, 0.5])
sigma_c = np.array([0.5, 0.5])


In [15]:
out2[sigma_r, sigma_c]

array([0., 0.])