# Teoria de Juegos
## Autor: Edinson Tolentino

Se instala las librerias del caso

In [1]:
!pip install nashpy

In [4]:
import nashpy as nash
import numpy as np

Definición del juego: piedra, papel y tijeras:

$$A = \begin{bmatrix} 0 & -1 & 1 \\ 1 & 0 & -1 \\ 1 & -1 & 0 \end{bmatrix}$$





Tabla de matrix, para dos jugadores (jugador fila y jugador columna)

|       | Piedra | Papel | Tijera |
|-------|--------|-------|--------|
|Piedra |  0,0   |  -1,1      | 1,-1       |
|Papel  |  1,-1      | 0,0      | -1,1       |
|Tijera |  -1,1      | 1,-1      |    0,0    |


In [5]:
A = np.array([[0,-1,1], [1,0,-1], [-1,1,0]])
out = nash.Game(A)
out

Zero sum game with payoff matrices:

Row player:
[[ 0 -1  1]
 [ 1  0 -1]
 [-1  1  0]]

Column player:
[[ 0  1 -1]
 [-1  0  1]
 [ 1 -1  0]]

### Juego de construcción de planta

El siguiente juego, muestra los impactos potenciales de la expansión de la capacidad de decisión de dos plantas:
- Toyota (jugador columa)
- Honda (jugador fila)

|       | Construir | No Construir |
|-------|--------|-------|
|Construir |  16,16   | 20,15      | 
|No Construir  |  15,20      | 18,18      |


In [8]:
H = np.array([[16,20], [15,18]])
T = np.array([[16,15],[20,18]])
out2 = nash.Game(H,T)
out2


Bi matrix game with payoff matrices:

Row player:
[[16 20]
 [15 18]]

Column player:
[[16 15]
 [20 18]]

### Juego dilema del prisionero

El siguiente juego, muestra las decisiones de dos posibles sospesochos de un crimen:
- J2 (jugador columa)
- J1 (jugador fila)

|       | Confesar | No Confesar |
|-------|--------|-------|
|Confesar |  -5,-5   | 0,-10      | 
|No Confesar  |  -10,0      | -1,-1      |

In [9]:
J1 = np.array([[-5,0], [-10,-1]])
J2 = np.array([[-5,-10],[0,-1]])
out3 = nash.Game(J1,J2)
out3

Bi matrix game with payoff matrices:

Row player:
[[ -5   0]
 [-10  -1]]

Column player:
[[ -5 -10]
 [  0  -1]]