# Teoria de Juegos
## Autor: Edinson Tolentino

### Tema: Definicion de juegos usando python

In [1]:
import nashpy as nash

In [2]:
A =[[3,1],[0,2]]
B =[[2,1],[0,3]]
battle_sex =nash.Game(A,B)


In [3]:
battle_sex

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [4]:
import numpy as np

In [6]:
p1 = np.array([[8,1],[15,3]])
p2 = np.array([[8,15],[1,3]])
pd = nash.Game(p1, p2)
pd

Bi matrix game with payoff matrices:

Row player:
[[ 8  1]
 [15  3]]

Column player:
[[ 8 15]
 [ 1  3]]

In [8]:
for eq in pd.support_enumeration():
    print(eq)
    

(array([0., 1.]), array([0., 1.]))


In [11]:
eq

(array([0., 1.]), array([0., 1.]))

## Juegos de pennies

In [12]:
A = np.array([[1,-1],[-1,1]])
mat_pennies =nash.Game(A)
mat_pennies


Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

La siguiente sintaxis evidencia la solución 

In [13]:
equilibrio = mat_pennies.support_enumeration()
for eq in equilibrio:
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))


## Dilema de prisionero

 


In [14]:
A = np.array([[-5,0],[-10,-1]])
B = np.array([[-5,-10],[0,-1]])
dilema =nash.Game(A,B)
dilema

Bi matrix game with payoff matrices:

Row player:
[[ -5   0]
 [-10  -1]]

Column player:
[[ -5 -10]
 [  0  -1]]

In [15]:
solucion = dilema.support_enumeration()
for eq in solucion:
    print(eq)

(array([1., 0.]), array([1., 0.]))
